import type { EncryptedPayload } from "../types";
import type {
  PaillierPublicKey,
} from "../zkp/types";

export type {
  PaillierPublicKey,
  HomomorphicEncryptedVote,
  ZKPVerificationReport,
  MerkleProof,
} from "../zkp/types";

/**
 * Configuration for AnonVoteClient.
 *
 * @example
 * ```typescript
 * import { AnonVoteClient } from "@anonvote/crypto/client";
 *
 * const client = new AnonVoteClient({
 *   ballotKey: crypto.randomBytes(32).toString("hex"),
 * });
 * ```
 */
export interface ClientConfig {
  /**
   * The per-ballot encryption key as a 64-character hex string (32 bytes).
   *
   * Must be generated fresh per ballot using `crypto.randomBytes(32).toString("hex")`.
   * Must never be the same key across two ballots.
   * Must never be stored in the database alongside encrypted votes.
   */
  ballotKey: string;

  /**
   * Optional Paillier public key for Zero-Knowledge Proofs and Additive Homomorphic Encryption.
   */
  paillierPublicKey?: PaillierPublicKey;
}

/**
 * Input parameters for creating a new election.
 */
export interface ElectionOptions {
  /** The title of the election. */
  title: string;
  /** A description of the election. */
  description: string;
  /**
   * The available voting options. Minimum 2, maximum 10.
   * These labels are never encrypted — only the generated option UUIDs reach the crypto layer.
   */
  options: string[];
  /** When the election opens for voting. */
  startTime: Date;
  /** When the election closes. Must be after startTime and in the future. */
  endTime: Date;
}

/**
 * A single option within an election.
 */
export interface ElectionOption {
  /** UUID generated per option — used as the optionId in votes. */
  id: string;
  /** The display label shown to voters. */
  label: string;
  /** Zero-based index of this option in the original options array. */
  index: number;
}

/**
 * An election created by AnonVoteClient.
 */
export interface Election {
  /** UUID generated by createElection. */
  id: string;
  title: string;
  description: string;
  options: ElectionOption[];
  startTime: Date;
  endTime: Date;
  createdAt: Date;
  status: "draft" | "active" | "closed" | "finalised";
}

/**
 * An encrypted ballot produced by castVote.
 *
 * The optionId field is present locally so the voter can confirm their choice
 * before submission. It is deliberately omitted when serialized for the server.
 */
export interface Ballot {
  electionId: string;
  /** The UUID of the chosen option. Present locally; never serialized to the server. */
  optionId: string;
  /** The AES-256-GCM encrypted payload — the only part sent to the server. */
  encryptedPayload: EncryptedPayload;
  createdAt: Date;
}

/**
 * A receipt confirming a vote was cast and the token used.
 */
export interface VoteReceipt {
  electionId: string;
  /** SHA-256 hash of the voter's token — proof of participation. */
  tokenHash: string;
  ballot: Ballot;
  submittedAt: Date;
}

/**
 * Result of verifying a ballot locally.
 */
export interface VerificationResult {
  confirmed: boolean;
  electionId: string;
  checkedAt: Date;
}
